### ISSUE TITLE
Column list ul (.Colvis_collection) should be removed when dataTables is removed

### ISSUE THREAD

**Issue by nMustaki** [DataTables/ColVis#26]
It's possible to bind on table removal (http://stackoverflow.com/questions/2200494/jquery-trigger-event-when-an-element-is-removed-from-the-dom).
What do you think ?

**Comment by DataTables** [comment]
Sorry for the massive time delay in fixing this. It [has now been](https://github.com/DataTables/ColVis/commit/9d409eedac072).
