### ISSUE TITLE
groupButtons collection is not being rebuilt on rebuild

### ISSUE THREAD

**Issue by rgavrilov** [DataTables/ColVis#31]
`rebuild` method has following code to clear `this.dom.buttons` collection:

    this.dom.buttons.splice(0, this.dom.buttons.length);

But there is no code to clear `this.dom.groupButtons` collection, following would do:

    this.dom.groupButtons.splice(0, this.dom.groupButtons.length);

As a result, calling `rebuild()` does not rebuilds `checked` and `indeterminate` properties' values on input elements.

**Comment by DataTables** [comment]
Nice one - thanks!
