### ISSUE TITLE
ColVis' stateChange callback function doesn't always trigger

### ISSUE THREAD

**Issue by gamut-was-taken** [DataTables/ColVis#32]
ColVis' stateChange callback function only triggers when an user clicks within a list item's label's content. The callback function doesn't trigger if an user clicks anywhere else in the list item.

http://jsfiddle.net/fL17ev1t/

**Comment by DataTables** [comment]
Thanks for the test case. This is just the oddest thing - if you click on the span element, two click events are triggered, causing two callbacks. [This commit](https://github.com/DataTables/ColVis/commit/65df8a51936c) fixes that, but causes the error you are seeing.

I can't figure out what is causing the double event - it just doesn't appear to make any sense!

What I would suggest at the moment is to forego the use of the stateChange callback and instead use [DataTables' `column-visibility` event](http://datatables.net/reference/event/column-visibility).

**Comment by gamut-was-taken** [comment]
I think I managed to replicate the issue here: http://jsfiddle.net/5m9os05y/

Clicking the span of the list item gets you two alerts instead of one like you'd expect. But using `change()` instead of `click()` apparently fixes the issue and I'm not sure why.

All I have to back me up is this SO comment here (though the page itself may help you to elucidate the issue): http://stackoverflow.com/questions/8238599/jquery-click-fires-twice-when-clicking-on-label#comment30702808_13756844

**Comment by DataTables** [comment]
Fixed in #35
