### ISSUE TITLE
ColVis + Fixed Columns broken (even FixedColumns official Colvis example)

### ISSUE THREAD

**Issue by woolyninja** [DataTables/ColVis#34]
So if you go to http://datatables.net/release-datatables/extensions/FixedColumns/examples/colvis.html and hide the first column you'll notice Last Name is populated with data from the Position column.

I'm having the exact same issue in my own project.

Any ideas on how to fix it?

**Comment by DataTables** [comment]
Hi,

Thanks for the bug report. [Fix is committed here](https://github.com/DataTables/FixedColumns/commit/c922b75a798). Please note that the fix will only operate correctly with DataTables 1.10+. Legacy versions of DataTables will still suffer from this issue, but there is no easy way to support them without adding a chunk of code.

The FixedColumns nightly is now up-to-date on the DataTables [downloads page](//datatables.net/download) if you want to use it.

**Comment by woolyninja** [comment]
Wow, thanks for the fast turnaround on this!  I'll try it later today.
