### ISSUE TITLE
fnRebuild - fnSettings() no longer exists...

### ISSUE THREAD

**Issue by bfreshour** [DataTables/ColVis#36]
It seems the DataTables object doesn't have a fnSettings method anymore.  It does have a settings() method.  I fixed the code by changing it to this, no idea if this is correct, but it's working for me.

		//nTable = oTable.fnSettings().nTable;
		nTable = oTable.settings()[0].nTable;

**Comment by DataTables** [comment]
It depends upon your initialisation `$().dataTable()` v `$().DataTable()`.

Either way, ColVis should abstract that out. Thanks for noting the bug.

**Comment by bfreshour** [comment]
This was my usage:

	var table = $("tblData").DataTable();
	$("tblData").on( 'column-visibility.dt', function ( e, settings, column, state ) {
    	console.log('Column '+ column +' has changed to '+ (state ? 'visible' : 'hidden'));
    	$.fn.dataTable.ColVis.fnRebuild( table );
	});
