### ISSUE TITLE
Missing groups option description in Options documentation page

### ISSUE THREAD

**Issue by ashl1** [DataTables/ColVis#41]
Hi
On the page http://datatables.net/extensions/colvis/options the 'groups' option is missing but presented in examples: http://datatables.net/release-datatables/extensions/ColVis/examples/group_columns.html. Could you please add the option to the Options documentation page?

**Comment by DataTables** [comment]
Thanks for pointing that out. This has now been committed and I'll push it out to the site soon.

I should note that ColVis will be retired next week when it is replaced by a new extension.

**Comment by ashl1** [comment]
I read about Buttons extension in 2.0 branch. Are you talking about that?
Thats really interesting to try that new extension just because I'm currenlty hardly worked in integratino DT and much more plugins and work on them.

**Comment by DataTables** [comment]
Yes - I've decided to fold ColVis into Buttons itself. So the 2 branch is now out of date and will be removed.

[Buttons is available here](https://github.com/DataTables/Buttons) and the `buttons.colvis.js` contains the column visibility buttons.

**Comment by ashl1** [comment]
Does the new Buttons Colvis support DT state saving as current do?
28 июля 2015 г. 15:06 пользователь "Allan Jardine" <notifications@github.com>
написал:

**Comment by DataTables** [comment]
Column visibility state is part of DataTables core, so yes, this should automatically simply work. Does it not?
