### ISSUE TITLE
Missing min.js and min.css in the bower dependency

### ISSUE THREAD

**Issue by jmelosegui** [DataTables/ColVis#42]
There is no min files in the bower package. It would be nice to have.

**Comment by DataTables** [comment]
They are available in the distribution distros. See [this blog post](http://datatables.net/blog/2015-11-09).

**Comment by sebastienbarre** [comment]
I don't think that's the case. Are you referring to ```https://github.com/DataTables/DataTables```?
The min files would be indeed useful.

**Comment by DataTables** [comment]
ColVis is legacy and retired software. It is no longer being developed having been replaced by Buttons.

There is no distribution repo for ColVis for that reason. Apologies for the incorrect response above, I must have been getting confused!

The debug and min versions are available on the DataTables CDN, but they will not be included in this repo nor will distribution versions of this repo be created. As I say, all development on this package has been terminated.
